global:

  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # O Prometheus está fazendo coleta do próprio servidor

  - job_name: 'nodejs'
    static_configs:
      - targets: ['10.0.21.151:3000']  # IP interno do seu servidor e a porta do seu app Node.js